# 1. Array Creations

In [1]:
import numpy as np

In [2]:
# NumPy stands for Numerical Python 
# Used for...
# Fast numerical computation, working with arrays and matrices, scientific computing, ML Data Science

# Easy

In [3]:
# Creating a NumPy array
arr = np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
# Cretaing a NumPy array with zeroes, lenght 5
arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [11]:
# Create a NumPy array with ones, length 4
arr2 = np.ones(4)
arr2

array([1., 1., 1., 1.])

# Medium

In [13]:
# create a numpy array starting from 10 to 50 with a step of 10
arr3 = np.arange(10, 51, 10)
arr3

array([10, 20, 30, 40, 50])

In [16]:
# Create a NumPy array of 5, equally spaced values between 0 and 1
arr4 = np.linspace(0, 1, 5)
arr4
# Creates equal gaps 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# Create a (3 x 3) NumPy array filled with value 9
arr5 = np.full((3, 3), 9)
arr5

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# Hard

In [21]:
# Create NumPy array (4 x 4), with integers inbetween 1 to 100
arr6 = np.random.randint(1, 100, size = (4, 4))
arr6

array([[79, 75, 17, 47],
       [ 2, 83, 56, 42],
       [92, 36,  1,  5],
       [31, 27, 42, 80]])

In [23]:
# Create a (5 x 5) identity matrix
arr7 = np.eye(5)
arr7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# create a 3D NumPy array of shape (2, 3, 4) with random floating-point numbers
arr8 = np.random.rand(2, 3, 4)
arr8

array([[[0.13300603, 0.73489952, 0.90126269, 0.128608  ],
        [0.19941177, 0.81809132, 0.87748783, 0.20601117],
        [0.52196247, 0.6223621 , 0.84942899, 0.50493136]],

       [[0.89363023, 0.98761969, 0.48747008, 0.98996451],
        [0.70345987, 0.03884999, 0.7378292 , 0.12975717],
        [0.68875728, 0.74663669, 0.97950243, 0.53815134]]])

# 2. Shape, Indexing and Basic operations

# Easy

In [30]:
arr9 = np.array([10,20,30,40,50])
arr9.shape

(5,)

In [33]:
# Access the last element
arr9[4]

50

In [37]:
# Multiply all elements by 2
arr9 * 2

array([ 20,  40,  60,  80, 100])

# Medium